services:
  data-tree:
    container_name: data-tree
    image: data-tree:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./:/app
    command: >
      sh -c "bun install && bun vite --host 0.0.0.0 --port 3000 --open"

